# Generated by Django 2.2.24 on 2022-11-30 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Наименование на русском')),
                ('title_jp', models.TextField(blank=True, verbose_name='Наименование на японском')),
                ('title_en', models.TextField(blank=True, verbose_name='Наименование на английском')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение')),
                ('description', models.TextField(blank=True, max_length=1000, verbose_name='Описание')),
                ('previous_evolution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_evolution', to='pokemon_entities.Pokemon', verbose_name='Эволюция')),
            ],
        ),
        migrations.CreateModel(
            name='PokemonEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(null=True, verbose_name='Широта')),
                ('lon', models.FloatField(null=True, verbose_name='Долгота')),
                ('appeared_at', models.DateTimeField(null=True, verbose_name='Появился')),
                ('disappeared_at', models.DateTimeField(null=True, verbose_name='Исчез')),
                ('level', models.IntegerField(null=True, verbose_name='Уровень')),
                ('health', models.IntegerField(null=True, verbose_name='Здоровье')),
                ('strength', models.IntegerField(null=True, verbose_name='Сила')),
                ('defence', models.IntegerField(null=True, verbose_name='Защита')),
                ('stamina', models.IntegerField(null=True, verbose_name='Выносливость')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon_entities.Pokemon')),
            ],
        ),
    ]
